### ISSUE TITLE
Revise december demo to use new pyciemss interface

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#121]
The following interfaces were tried on the december demo.
- [x] setup_model, 
- [ ] reset_model, 
- [x] intervene, 
- [x] sample, 
- [x] calibrate, 
- [x] optimize, 
- [ ] load_petri_model

we did not try `load_petri_model` because we are using `pyciems.PetriNetODE.models.MIRA_I_obs_with_scaled_Gaussian_noise`

**Comment by anirban-chaudhuri** [comment]
`optimize` has been updated and Decemeber demo notebook has all the revised code. See PR #171
