### ISSUE TITLE
Move incident-to-census data processing utilities to a tested python file

### ISSUE THREAD

**Issue by SamWitty** [ciemss/pyciemss#138]
Currently data processing utilities for transforming incident data to census data live in a jupyter notebook (notebook/april_ensemble/covid_data/Covid_hosp_data.ipynb) and are untested.

These should be moves into the `utils` folder, with tests added.

**Comment by sabinala** [comment]
I'm closing this issue (a) because it's old, and (b) because these utilities do now live in the poorly named utils file: https://github.com/ciemss/pyciemss/blob/main/src/pyciemss/utils/toronto_ensemble_challenge_utils.py
