### ISSUE TITLE
Create custom rate laws from AMR expression

### ISSUE THREAD

**Issue by SamWitty** [ciemss/pyciemss#145]
Currently we ingest MIRA models to extract the parameter names, parameter values, petri net structure, and conversion types, all while implicitly assuming that the input model satisfies a standard mass action dynamics. However, this restriction is not intrinsic to MIRA models, instead MIRA models also come with rate laws per transition that allow for near arbitrary specification of differential equations.

To address this issue we should ingest those rate laws directly. 

One possible approach is to parse the symbolic expression using something like `sympy`.

**Comment by djinnome** [comment]
Hi @SamWitty with the new `Observables` feature in the ASKEM Model representation, it should be possible to generate an observation function automagically from the AMR.  This is an enhancement, but if we want to be able to calibrate on aribitrary data-model mappings that were specified in the AMR, this issue would address that concern.

**Comment by djinnome** [comment]
Now that we have the ability to compile rate laws using SymPytorch, let's put this back on the front burner.
