### ISSUE TITLE
Implement ASKEM Model representation for Petri Nets

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#152]
Currently, we can only load an epidemiology model using the mira json representation. 
Joshua asked us to write code that can directly load the new [ASKEM model representation](https://github.com/DARPA-ASKEM/Model-Representations/blob/main/petrinet/examples/sir.json)

The preferred plan is to leverage mira tools for deserializing the ASKEM model representation into a mira petri net and then load the mira object into a `MiraPetriNetODESystem`

**Comment by SamWitty** [comment]
Completed.
