### ISSUE TITLE
Deterministic models are a bit awkward

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#157]
Suppose we want to generate a deterministic version of an SIR model.

Currently, reading from MIRA and setting `add_uncertainty=False` assigns each parameter to a `pyro.Parameter`
Is this what we want?  You can't `calibrate` such a model, or `intervene` on it.

An alternative is to generate random variables for each parameter using `add_uncertainty=True` and then intervene on those parameters to set them to the desired value.  However, every static parameter intervention requires a separate timepoint and the timepoint must be after the start event.  If you want the trajectory to use the intervened parameters then it also needs to be set before the `tspan` of the `sample`.  This is not a show-stopper, just a bit awkward, which could be alleviated with some higher-level function such as in issue https://github.com/ciemss/pyciemss/issues/107

**Comment by ShantMahserejian** [comment]
New notebook to test and produce errors/challenges:

1. Create new hand-written SIR model without uncertainty
- [ ] Modifying the beta & gamma parameters, with pyro.Parameters and their initial values in the param_prior method
- [ ] Test calibration with the deterministic version of this model (load model with "add_uncertainty = False")

2.  Use existing MIRA model
- [ ] Repeat deterministic model test
