### ISSUE TITLE
Sanity checks for TA2 models

### ISSUE THREAD

**Issue by ShantMahserejian** [ciemss/pyciemss#159]
Need to establish quality checks and potential issues for TA2 models coming down the pipeline. Create unit-tests to determine potential errors and mismatches between different models and initial states. 

Possible unit-tests include:
- Check that the sum of initial conditions equals the expected total population to which the parameters have been calibrated
- Check that the scaled initial conditions from different models are in agreement when considering an ensemble model

Other considerations:
- How to map between observed data and model state variables, for both initial conditions and observation models
- How to deal with uncertainty in the initial conditions

**Comment by sabinala** [comment]
What do you want to do about this issue? I think it would be a good idea to have a unit test to check that the sum of the initial conditions equals the total population, but it seems the other concerns listed have been addressed either by adding observables or because "add uncertainty" is no longer the default.

**Comment by djinnome** [comment]
Although the specific unit tests suggested have already been implemented, the general question about sanity checks for reasonable inputs to models remains.  Similar to https://github.com/ciemss/pyciemss/issues/219 this issue could be closed by https://github.com/ciemss/pyciemss/pull/243

**Comment by sabinala** [comment]
As far as reasonable inputs to models, could this problem be solved by FUNMAN? I never heard back from Dan Bryce about this, but from my understanding, FUNMAN is able to give "allowable" ranges for parameters and initial conditions.

**Comment by SamWitty** [comment]
Closing. Please feel free to parse this out into more fine-grained specific issues as needed.

**Comment by SamWitty** [comment]
See e.g. #273 or #288 .
