### ISSUE TITLE
Add PetriNetODE.from_ASKENET() method

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#170]
@SamWitty  said:

> Ben sent me a link to a PR that integrates MIRA with the ASKEM-model representation. 
> Could someone volunteer to add a small function and interface that is similar to from_MIRA in the PetriNetODE class?
> https://github.com/indralab/mira/pull/173

**Comment by djinnome** [comment]
waiting on https://github.com/indralab/mira/issues/175

**Comment by ShantMahserejian** [comment]
Issue #177 would also benefit from this task completion
