### ISSUE TITLE
Prior distributions over initial conditions

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#174]
At the TA2 meeting today, the question of providing a full initial conditions was pushed back to TA3 as a calibration issue.

If that is the case, then we cannot expect to receive a full set of intitial conditions, so we should think about whether to add  a feature to allow uncertainty in our initial conditions.

@SamWitty

**Comment by anirban-chaudhuri** [comment]
Is this the same as #139 ? I am closing it for now. We can reopen it if I misunderstood the difference with the other issue.
