### ISSUE TITLE
Convert hand-rolled ensemble models to Askem model representation

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#175]

**Comment by djinnome** [comment]
Use this `AskeNetPetriNet` model as a guide

https://github.com/indralab/mira/blob/288136b345911c9ed2ead9954a210f2e2a51b628/mira/modeling/askenet/petrinet.py#L28

**Comment by sabinala** [comment]
I am closing this issue, as it was completed on branch #177 for pull request #178
