### ISSUE TITLE
Investigate ComplexVid configuration and execution

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#176]
"Social interaction layers in complex networks for the dynamical epidemic modeling of COVID-19 in Brazil." Physica A: Statistical Mechanics and its Applications 564 (2021): 125498. Leonardo F. S. Scabini, Lucas C. Ribas, Mariane B. Neiva, Altamir G. B. Junior, Alex J. F. Farfán, Odemir M. Bruno

https://github.com/scabini/COmplexVID-19.git

**Comment by djinnome** [comment]
Keep an eye on Kris Brown's implementation of ComplexVid, but make sure the python version works in your hands.

Kristopher Brown and David I. Spivak. 2023. Dynamic Tracing: a graphical language for rewriting protocols. arXiv (2023). DOI:https://doi.org/10.48550/arxiv.2304.14950

https://github.com/kris-brown/Complexvid.jl

**Comment by sabinala** [comment]
This has been investigated, but it seems ABMs are on hold for now, so I'm closing this issue.
