### ISSUE TITLE
Expected behaviour for `add_uncertainty` in `load_*_sample` functions

### ISSUE THREAD

**Issue by liunelson** [ciemss/pyciemss#184]
@SamWitty 
Currently, the `load_*_sample` functions have a `add_uncertainty` boolean argument. Setting it to `True` causes all priors that may be in the input model to be replaced by a +/- 10% uniform distribution.

I think the expected behaviour could be:
1. `add_uncertainty = False` -> the simulator accepts the model parameter values at face value (int, float, prior distribution)
2. `add_uncertainty = True` -> the simulator replaces any non-distribution values (int, float) by a +/- 10% uniform distribution.

The `10` could be an optional argument too or be replaced by the min/max given in the model metadata.

**Comment by SamWitty** [comment]
Closing as `add_uncertainty` has been removed.
