### ISSUE TITLE
Produce results in CDC Forecast Hub compliant form

### ISSUE THREAD

**Issue by brandomr** [ciemss/pyciemss#198]
See [example output](https://raw.githubusercontent.com/reichlab/covid19-forecast-hub/master/data-processed/JHUAPL-Bucky/2022-06-20-JHUAPL-Bucky.csv). This is required for the 12 month ensemble challenge. Includes providing quantiles as output. See https://covid19forecasthub.org/doc/reports/ for more

**Comment by SamWitty** [comment]
Discussed w. TA4. They will take this on.
