### ISSUE TITLE
Error required: check that units in AMR are internally consistent

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#216]
We need unit tests that check to make sure that consistent dimensions and units are being used among model variables and parameters, and between the data and the model variables and parameters

**Comment by SamWitty** [comment]
@djinnome , could you please complete the description for this issue or close it? Thanks!

**Comment by djinnome** [comment]
I looked into the AMR, and there is no explicit annotation of dimensions or units. The closest thing is the DKG identifiers, and I don't think that has enough information to perform a dimensional analysis.  I suppose we can assume that parameters are 1/day, that compartments are people and that fluxes are people/day, and then perform dimensional analysis, but without a set of clear use cases that would fail or pass, I am not sure this is actionable.

**Comment by djinnome** [comment]
I did find one model that had units: https://github.com/DARPA-ASKEM/simulation-integration/blob/main/data/models/SEIRHD_base_model01_petrinet.json

So at least I could perform a dimensional analysis on the rate law to make sure it works out to person/day.

**Comment by djinnome** [comment]
Since we are already using sympy, I think https://docs.sympy.org/latest/modules/physics/units/index.html is probably the simplest way to perform dimensional analysis.

**Comment by djinnome** [comment]
Questions:

* Is person a dimension, a unit, or a quantity?

**Comment by SamWitty** [comment]
@djinnome , should this be re-opened now that you've found an AMR with units?

**Comment by djinnome** [comment]
Honestly, there isn't much to do for Epi models, but I think the dimensional analysis will be critical for managing the complexity of climate models in phase 2.
