### ISSUE TITLE
test all models in AMR to see if they can be loaded

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#219]
@liunelson ran into an issue loading rate laws in SIDARTHE that we should have found first.
`BIOMD0000000955_askenet.json`

**Comment by SamWitty** [comment]
@djinnome , I'm not sure how to interpret this issue. Can it be closed?

**Comment by SamWitty** [comment]
Closed, as this is subsumed by using the model representations repo as a gold standard.
