### ISSUE TITLE
Covid-19 Data avoids missing data

### ISSUE THREAD

**Issue by ShantMahserejian** [ciemss/pyciemss#241]
The method to generate covid data in `toronto_ensemble_challenge_utils.py` avoids missing data. This creates data that misses a significant time duration, including early timepoints that are needed to perform calibratation in Scenario 1 - Part 2 (e.g. we are missing time between the first case was detected and implementing a mask mandate. The current data set only includes data well after the mask mandate was implemented).

The fix is easy, but can impact how calibration is handled. Does `calibrate` handle missing data?

**Comment by djinnome** [comment]
We currently assume that the data is missing at random.  If we have reason to believe that is not the case, we can also attempt to model the missingness mechanisms.

**Comment by ShantMahserejian** [comment]
@djinnome the issue was an actual error triggered by missing entries in the training data.

The pull request associated with this fix has been accepted

**Comment by ShantMahserejian** [comment]
@djinnome the issue was an actual error triggered by missing entries in the training data.

The pull request associated with this fix has been accepted
