### ISSUE TITLE
Enable an "all-but" option on trajectory plot

### ISSUE THREAD

**Issue by JosephCottam** [ciemss/pyciemss#293]
When you know what you DON'T want to see, it may be hard to specify what to still show using only 'subset' semantics.

(Vignesh requested this in the context of ensemble models)

**Comment by JosephCottam** [comment]
Plan:
- Rename 'subset' to 'keep'
- Add a parameter 'drop' that lets you drop specific things
- Both are allowed at the same time.  As an arbitrary decision, 'keep' will execute before 'drop'.  (I don't know that it will ever matter, but its what I'm choosing.) 
- If 'drop' element is not found, that's OK (moves on silently).

**Comment by VigneshSella** [comment]
Just adding that this will also be very useful in the context of the stratified models which have ~80 parameters or so.
