### ISSUE TITLE
Mouse-over data to highlight legend

### ISSUE THREAD

**Issue by JosephCottam** [ciemss/pyciemss#294]
When you mouse-over the legend, it highlights the line/span in a trajectory plot.  However, when you mouse-over the line/etc. it doesn't highlight the legend.  When searching for things, it would be _nice_ to have that feedback (e.g., when the colors repeat or the band color is obscured by context).

**Comment by JosephCottam** [comment]
@marjoleinpnnl I thought this issue was fixed.  Could you verify that it is in main?  If it is, please close this issue.  If not...let's track down where it is.

**Comment by marjoleinpnnl** [comment]
added in pull request https://github.com/ciemss/pyciemss/pull/336
