### ISSUE TITLE
Odd behavior when plotting data

### ISSUE THREAD

**Issue by sabinala** [ciemss/pyciemss#317]
<img width="666" alt="Screenshot 2023-08-04 at 2 26 45 PM" src="https://github.com/ciemss/pyciemss/assets/130604122/e06bfae9-314c-41ec-93f7-82089919abc0">

It appears that the data is being plotted as one long list rather than for each column separately (by state variable).

That is, case data is plotted, and then the last case datapoint is connected to the first hosp datapoint...even though it knows to label and color them differently.

**Comment by JosephCottam** [comment]
@sabinala  Can you prep a notebook that exhibits the behavior for me?  

I can think of two ways this could happen and one involves me doing something wrong internally and the other involves the data being prepped in a way I'm not expecting (which would still be my problem...but maybe at the documentation level and maybe at the I-need-to-handle-a-case-I-wasn't-expecting-to level).  A notebook would help me distinguish my three options.

**Comment by sabinala** [comment]
Hi @JosephCottam, I created a branch for this issue and make a little notebook in the `july_evaluation` folder [here](https://github.com/ciemss/pyciemss/blob/317-odd-behavior-when-plotting-data/notebook/july_evaluation/Vega_Plot_Issue317.ipynb). Let me know if you have any questions. Thanks!

**Comment by JosephCottam** [comment]
I have found the mistake. The trajectories schema uses a "group mark" and splits the data by "trajectory" BUT the exemplar points still referred the un-split data.  I have a fix now, and am writing a schema-lint-like-test to check for this in the future.
