### ISSUE TITLE
Re-formatting quantile results works for some but not all output

### ISSUE THREAD

**Issue by sabinala** [ciemss/pyciemss#319]
I saved the part I output from `load_and_calibrate_and_sample_ensemble_model` like so: `result1["quantiles"].to_csv("../../notebook/ensemble_eval_sa/ensemble_results/partI_ensemble_of_one_quantiles.csv", index=False)`

And when I take this output and use:
```python
from pyciemss.utils.interface_utils import cdc_reformatcsv

q_ensemble_data = cdc_reformatcsv(filename="../../notebook/ensemble_eval_sa/ensemble_results/partI_ensemble_of_one_quantiles.csv", 
                                  solution_string_mapping={"I": "cases", "D": "deaths"}, 
                                  forecast_start_date="2020-04-03",
                                  location="New York State",
                                  drop_column_names=["timepoint_id", "number_days", "inc_cum", "output", "Forecast_Backcast"])
q_ensemble_data.to_csv("../../notebook/ensemble_eval_sa/ensemble_results/partI_ensemble_of_one_forecast_quantiles_Apr032020.csv")
```

I get a csv with the correct formatting. However, when trying the same thing (below) for results from part II, I get an empty csv :(

```python
from pyciemss.utils.interface_utils import cdc_reformatcsv

q_ensemble_data = cdc_reformatcsv(filename="../../notebook/ensemble_eval_sa/ensemble_results/partII_ensemble_of_one_quantiles_day0_Jun032021.csv", 
                                  solution_string_mapping={"I": "cases", "H": "hospitalizations", "D": "deaths"}, 
                                  forecast_start_date="2021-07-15",
                                  location="New York State",
                                  drop_column_names=["timepoint_id", "number_days", "inc_cum", "output", "Forecast_Backcast"])
q_ensemble_data.to_csv("../../notebook/ensemble_eval_sa/ensemble_results/partII_ensemble_of_one_forecast_quantiles_Jul152021.csv")
```

**Comment by djinnome** [comment]
A little extra context:

```python
import pandas as pd
quantiles_file = "ensemble_results/partII_ensemble_of_one_quantiles_day0_Jun032021.csv"

quantiles = pd.read_csv(quantiles_file)
quantiles.head()
```

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>timepoint_id</th>      <th>number_days</th>      <th>inc_cum</th>      <th>output</th>      <th>type</th>      <th>quantile</th>      <th>value</th>      <th>Forecast_Backcast</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>0</td>      <td>0.0</td>      <td>inc</td>      <td>I</td>      <td>quantile</td>      <td>0.010</td>      <td>64.0</td>      <td>Backcast</td>    </tr>    <tr>      <th>1</th>      <td>0</td>      <td>0.0</td>      <td>inc</td>      <td>I</td>      <td>quantile</td>      <td>0.025</td>      <td>64.0</td>      <td>Backcast</td>    </tr>    <tr>      <th>2</th>      <td>0</td>      <td>0.0</td>      <td>inc</td>      <td>I</td>      <td>quantile</td>      <td>0.050</td>      <td>64.0</td>      <td>Backcast</td>    </tr>    <tr>      <th>3</th>      <td>0</td>      <td>0.0</td>      <td>inc</td>      <td>I</td>      <td>quantile</td>      <td>0.100</td>      <td>64.0</td>      <td>Backcast</td>    </tr>    <tr>      <th>4</th>      <td>0</td>      <td>0.0</td>      <td>inc</td>      <td>I</td>      <td>quantile</td>      <td>0.150</td>      <td>64.0</td>      <td>Backcast</td>    </tr>  </tbody></table>

```python
q_ensemble_data = cdc_reformatcsv(filename=quantiles_file, 
                                  solution_string_mapping={"I": "cases", "H": "hospitalizations", "D": "deaths"}, 
                                  forecast_start_date="2021-07-15",
                                  location="New York State",
                                  drop_column_names=["timepoint_id", "number_days", "inc_cum", "output", "Forecast_Backcast"])
q_ensemble_data
```

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>type</th>      <th>quantile</th>      <th>value</th>      <th>target</th>      <th>forecast_date</th>      <th>target_end_date</th>      <th>location</th>    </tr>  </thead>  <tbody>  </tbody></table>

**Comment by anirban-chaudhuri** [comment]
It seems the Part II file only has backcasting (predictions where data is already available) and no forecasting beyond the currently observed data. The CDC format deletes all the rows for "backcast" and only reports forecast data.

**Comment by anirban-chaudhuri** [comment]
I think the issue is with the data file: https://github.com/ciemss/pyciemss/blob/sa-ensemble-eval/notebook/ensemble_eval_sa/datasets/NY_data2.csv. 
I believe the first column should align with the timepoints you are using in the calibration. At the moment, it goes from 500-539 but I think it should go from 0-39.
