### ISSUE TITLE
April Ensemble examples not longer work

### ISSUE THREAD

**Issue by JosephCottam** [ciemss/pyciemss#325]
A change in the interface for `setup_model` makes it so the notebooks no longer as written.  Earlier there were parameters for `psuedocounts` that have been removed.

A change either `convert_to_output_format` or in the data generating process mean that there can be duplicate values on the index.  This causes problems when composing data from different runs. The gist of the problem is that if you have a two series with multiple "Day 1" entries on the index, how should they be matched up?  Two simple (but probably not correct options) are:
- In order of appearance?  But appearance order is somewhat arbitrary and what if one of the series has two "Day 1" entries and the other has three?  Do you drop some?
- Cross-product?  This multiplies the number of entries, but has really odd semantics for time-series data.
- Drop all but one appearance? But which do you drop?

**Comment by djinnome** [comment]
The parameters, observables,  state variables ids need to be globally unique,  but in some of the Biomodels AMRs, that is not the case.   The simplest solution is to flag the AMR in MIRA before it even gets to pyciemss.  Any other solution involves tradeoffs, as Joseph has alluded to.

**Comment by djinnome** [comment]
@JosephCottam can you provide a simple test that triggers this bug?

**Comment by JosephCottam** [comment]
The issues are evident in when trying to run https://github.com/ciemss/pyciemss/blob/main/notebook/april_ensemble/demo.ipynb

My first pass at "fixing" are in https://github.com/ciemss/pyciemss/blob/325-april-ensemble-examples-not-longer-work/notebook/april_ensemble/demo.ipynb.

The  branch linked to this issue includes a fix to the first bug (I think...I could use a double-check that I did it right). 

The second one I'm not sure the origin of yet, so the notebook only includes a hack that drops duplicates.  That's probably the WRONG thing to do, but it was expedient.  (Look for the cell with the `#HACK` comment.)

I did some looking since I started documenting the issue.  I think it is related to the ensemble nature of that notebook.  The duplicates always come in triples and there are three models.   This implies that there is probably something else that belongs on the index.  Since I setup the index, I'm wading through the issue now.

**Comment by JosephCottam** [comment]
@sabinala [This notebook](https://github.com/ciemss/pyciemss/blob/325-april-ensemble-examples-not-longer-work/notebook/april_ensemble/syndata_generate_and_test.ipynb) won't run and @djinnome thinks you might know how to fix!

The cell under the title "Set up and intervene on Model 2 with fixed parameters" is the issue.  I checked it in with the error message displayed for your convenience. (The next cell does a similar thing to model 3 and has the same issue).

Do you know how to fix this issue?  Can you give it a go?

**Comment by sabinala** [comment]
It looks like it's no longer running because we're not combining parameters anymore. As in, beta*1/N no longer becomes "mira_parameter_0". I can fix this, but it'll take me a minute to go back and find what each of those mira-parameters was originally.

**Comment by sabinala** [comment]
Just pushed my fix for this, all is working now and I believe this issue can be closed :)

**Comment by djinnome** [comment]
Hi @sabinala if this is all working now, please update the label on the PR #330 to `awaiting review` and assign a reviewer to approve the PR.

**Comment by SamWitty** [comment]
See comment in #330
