### ISSUE TITLE
Extend test_amr to update cached copies

### ISSUE THREAD

**Issue by JosephCottam** [ciemss/pyciemss#326]
We currently cache the AMR specs for testing purposes.  New AMRs maybe published and old ones sometimes receive updates (as the AMR spec changes).  

Add a flag to the script-execution of test_amr that will update all the currently downloaded copies and grab new ones.  Something like "--update-cached" as part of generating the expected pass/fail file.

**Comment by SamWitty** [comment]
Closed because of change to AMR testing strategy.
