### ISSUE TITLE
Set up ASKEM integration github action

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#332]
https://docs.google.com/document/d/1_RvLMZ3KZChyR02yn-EdeOJWi9QmdrzUPZYgxKp48Y4/edit#heading=h.5x0d5h95i329

**Comment by brandomr** [comment]
I can add this in a PR if helpful but you'll need to add the PAT to the repo

**Comment by djinnome** [comment]
This issue is addressed by #346

**Comment by djinnome** [comment]
@brandomr reviewed and accepted the merge request
