### ISSUE TITLE
Consolidate notebooks and clean up older ones

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#333]
maintaining notebooks for older scenarios is a challenge.  On the one hand, most of these notebooks would require a complete refactor. On the other hand, these scenarios are useful for demonstrating the value of our software.  The task here is to thread that needle and triage the older notebooks in what needs working immediately, what is not worth getting to work, and what notebooks need would be nice to fix, but is not a priority.

**Comment by djinnome** [comment]
What we have decided so far:

# Update immediately
- [ ] Evaluation scenarios
- [ ] April ensemble
- [ ] December demo

**Comment by SamWitty** [comment]
@ShantMahserejian , any update on progress towards this issue?

**Comment by SamWitty** [comment]
Closing, as all notebooks except the integration demo have been removed.
