### ISSUE TITLE
PyTorch interface to a SciML solver that exposes gradients and event handling

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#334]
If CIEMSS is to be compositional with JuliaSim, then one way to separate concerns is to specify an ODE or PDE on the python side  and pass it to PyTorch, which gets solved on the SciML side.  The SciML solver needs to support gradients and event handling and expose those gradients and events to PyTorch.

**Comment by SamWitty** [comment]
@djinnome , is this an issue for us or for the JuliaSim folks? If for us, could you please rewrite this in a way that describes what tasks we need to complete?

**Comment by djinnome** [comment]
It is a placeholder issue for JuliaSim folks until https://github.com/SciML/diffeqpy/issues/115 is exposed to the [DARPA ASKEM integration project](https://github.com/orgs/DARPA-ASKEM/projects/5) through github actions.

**Comment by SamWitty** [comment]
In that case, could you make the it a placeholder issue on the https://github.com/DARPA-ASKEM/simulation-service repo?

**Comment by djinnome** [comment]
Done: https://github.com/DARPA-ASKEM/simulation-service/issues/108
