### ISSUE TITLE
Optionally return Pyro object

### ISSUE THREAD

**Issue by fivegrant** [ciemss/pyciemss#343]
There is a request to [store the Pyro simulation object](https://github.com/DARPA-ASKEM/pyciemss-service/issues/29). If you could return the object in the dictionary provided by each of the interfaces, we could save it pickled to S3 on the service side.

**Comment by SamWitty** [comment]
@fivegrant , once #358 lands the pyro calibration object will be available from the dictionary `result = load_and_calibrate_and_sample_petri_model(...)`. Specifically, it is available at `inferred_parameters = result["inferred_parameters"]`.
