### ISSUE TITLE
Publish PyCIEMSS to PyPI OR start tagging releases

### ISSUE THREAD

**Issue by fivegrant** [ciemss/pyciemss#344]
TA4 is trying to ensure builds are more reproducible (Here's the [issue tracking this on the PyCIEMSS Service side](https://github.com/DARPA-ASKEM/pyciemss-service/issues/35)).

Currently, the service grabs PyCIEMSS by the revision hash, but we would ideally like to grab releases instead. Additionally, the MIRA requirement is not locked so this can cause an unexpected update downstream. Tagging PyCIEMSS and MIRA would go a long way in making sure builds are more reliable.

**Comment by SamWitty** [comment]
@fivegrant , we've now tagged our first 0.0.1 release on PyCIEMSS, and will continue to follow good semantic versioning practices with regular tagged released moving forward. This will include changes to `setup.cfg` in PyCIEMSS to match the tagged release.
