### ISSUE TITLE
Provide documentation for pyciemss services that have not been integrated into Terarium yet

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#361]
For the Quarterly report, we mentioned that the following pyciemss services are ready to be integrated into Terarium.  These include:

- [ ] Risk-based optimization under uncertainty
- [ ] Simulation prognostic and diagnostic visualizations (Bayesian workflow) 
- [ ] Hybrid deterministic/probabilistic calibration
- [ ] Ensemble Calibration & Simulation

Because prioritization is a distributed decision, we think it is best to provide sufficient documentation to describe the features and what kinds of scenarios they will be useful for so that TA4 and MITRE can make informed decisions.

For example, most of the scenario 2 questions in the January hackathon required risk-based optimization under uncertainty.  But a big part of the July hackathon required ensemble methods and combinations of deterministic and probabilistic simulations in scenario 3.  With that said, future scenarios are likely to have long-running computations that require users to have access to proper diagnostics before, during and after simulations, so that is an argument for prioritizing the Bayesian workflow.

**Comment by anirban-chaudhuri** [comment]
Do you mean as a separate document or as the description under the specific TA4 interface functions? There is a description of the inputs and outputs for the risk-based OUU in the TA4 interface functions.

**Comment by SamWitty** [comment]
Closing this issue, as it's about general CIEMSS project management and not PyCIEMSS development specifically.
