### ISSUE TITLE
Possible discrepancy between values in "data" and "inferred_parameters" in the result of model calibration

### ISSUE THREAD

**Issue by liunelson** [ciemss/pyciemss#368]
I've been exploring the new calibration interfaces that @SamWitty @anirban-chaudhuri have set up for integration. In particular, I'm looking at the `inferred_parameters` key in the output of `load_and_calibrate_and_sample_petri_model(...)` and `load_and_calibrate_and_optimize_and_sample_petri_model(...)` functions.

I followed the [demo](https://github.com/ciemss/pyciemss/blob/main/notebook/integration_demo/demo.ipynb) notebook to run a calibration of a SIDARTHE model with 16 parameters. I computed the marginal distribution of the joint posterior distribution along two parameters of interest (`beta, gamma`) and plotted it in addition to the parameter samples (red markers) in the `data` key of the output.

![Screenshot 2023-09-06 at 15 22 59](https://github.com/ciemss/pyciemss/assets/1030720/cd741a1a-b45c-49d3-9ac8-363e4d7d4c18)

![Screenshot 2023-09-06 at 15 41 06](https://github.com/ciemss/pyciemss/assets/1030720/b7b3822e-82ec-41dc-aff0-288ca06aa130)

This code is at Line 162-197 [here](https://github.com/liunelson/pyciemss/blob/nl-test/notebook/integration_demo/nliu/review_interfaces.py)
```
# Get parameter mesh ranges
n = 10
p1 = "beta"
p2 = "gamma"
mesh_params = {
    "_".join(c.split("_")[:-1]): [results_calibrated["data"][c].min(), results_calibrated["data"][c].max(), n]
    if "_".join(c.split("_")[:-1]) in (p1, p2)
    else [results_calibrated["data"][c].min(), results_calibrated["data"][c].max(), 1]
    for c in results_calibrated["data"].columns if c.split("_")[-1] == "param"
}

# Evaluate probability density over given parameter mesh
params, density = get_posterior_density_mesh_petri(
    inferred_parameters = results_calibrated["inferred_parameters"],
    mesh_params = mesh_params
)

# Marginalize all other parameters
axes = tuple([i for i, p in enumerate(params) if p not in (p1, p2)])
marginal_density = density.sum(axis = axes)
s = tuple([slice(None) if p in (p1, p2) else slice(0, 1) for p in params.keys()])
x = params[p1][s].squeeze()
y = params[p2][s].squeeze()

# Plot marginal distribution
fig, ax = plt.subplots(1, 1, figsize = (8, 8))
i = ax.pcolormesh(x, y, marginal_density)
__ = plt.setp(ax, xlabel = p1, ylabel = p2, title = f"Marginalized Parameter Distribution from Model Calibration")
__ = fig.colorbar(i, ax = ax)

x0 = results_calibrated["data"][results_calibrated["data"]["timepoint_id"] == 0][p1 + "_param"]
y0 = results_calibrated["data"][results_calibrated["data"]["timepoint_id"] == 0][p2 + "_param"]
__ = ax.scatter(x0, y0, marker = '.', color = 'red')
```

Is it expected that the distribution implied by the `data` samples is not aligned with the associated marginal distribution of the joint posterior parameter distribution?

I imagine that I might have incorrectly marginalized the joint distribution or both quantities are not actually directly comparable, hence explaining the discrepancy.

**Comment by liunelson** [comment]
^ I can't actually assign anyone or tag it to the integration board from here. Someone else could do that!

**Comment by liunelson** [comment]
@SamWitty Yep, it's [here](https://github.com/liunelson/pyciemss/blob/nl-test/notebook/integration_demo/nliu/review_interfaces.py)

**Comment by SamWitty** [comment]
@liunelson , sorry for the delay in looking into this for you. I was on vacation last week and just now getting back to things.

Thanks for sharing the notebook. Could we schedule some time this week to go through it together? Feel free to follow up on slack.

**Comment by SamWitty** [comment]
Closing, as this feature has been removed from PyCIEMSS.
