### ISSUE TITLE
Bug report: Optimize integration interface gives assertion error

### ISSUE THREAD

**Issue by liunelson** [ciemss/pyciemss#377]
We're in the process of integrating the `load_and_optimize_and_sample_petri_model` interface.
An assertion error is returned when the `timepoints` array contains a time point when an intervention is also applied.

@fivegrant first encountered it and I was able to replicate it here:
https://github.com/liunelson/pyciemss/blob/nl-test/notebook/integration_demo/nliu/test.py

To replicate, set `interventions = [(20.0, "beta")]` and `timepoints = [0.0, 1.0, 20.0]`.

![Screenshot 2023-09-15 at 11 55 30](https://github.com/ciemss/pyciemss/assets/1030720/1e3bb3bd-f935-4881-8bfc-988615ddf826)

@JosephCottam, could you flag this as "integration" and tag whoever could confirm that this is a bug and patch it?

**Comment by anirban-chaudhuri** [comment]
Since the bigbox interface is obsolete now, the new optimize interface should solve this issue.
