### ISSUE TITLE
Bug report: type hinting in interfaces.py

### ISSUE THREAD

**Issue by liunelson** [ciemss/pyciemss#378]
@fivegrant and I encountered this issue during integration.

The function `scenario2dec_nday_average` requires its argument to be of type `int`. Otherwise, we get a slice error.

The typing hinting should be replaced with `Tuple[str, str, int]` (or whatever is the correct one for a list of arguments `**args`) In this line and similar:
https://github.com/ciemss/pyciemss/blob/5899664bfd0126b237a319ce77a3d49436d18e12/src/pyciemss/PetriNetODE/interfaces.py#L547

**Comment by anirban-chaudhuri** [comment]
This has been changed to qoi being a user-defined callable function with `scenario2dec_nday_average` as an example.

**Comment by SamWitty** [comment]
Closing as the issue is now out of date.
