### ISSUE TITLE
Increase Test Coverage of Visualization Modules

### ISSUE THREAD

**Issue by JosephCottam** [ciemss/pyciemss#385]
The individual visualizations are not exercising a lot of some plot functionality.
We need to bring the test coverage up by either removing code or extending tests to cover more cases.

Coverage as-of 3Oct2023:
src/pyciemss/visuals/barycenter.py: 14%
src/pyciemss/visuals/calibration.py: 25%
src/pyciemss/visuals/checks.py: 91%
src/pyciemss/visuals/graphs.py: 20%
src/pyciemss/visuals/histogram.py: 100%
src/pyciemss/visuals/plots.py: 90%
src/pyciemss/visuals/trajectories.py: 61%
src/pyciemss/visuals/vega.py:    84%

**Comment by SamWitty** [comment]
Closed as covered by #469
