### ISSUE TITLE
Add tests for load_data to robustly handle typical csv issues.

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#434]
The new interface for `calibrate` requires csv files, but there are lots of ways that csv files can fail to provide information in the right format.  Test the most common failure modes, such as:

* missing data
* incorrectly typed columns
* mislabled columns
* header columns have one fewer column than data
* alignment issues
* Escaping commas
* Na, NaN, None, '',,

All of these issues will make it difficult to convert a dataframe to a correctly typed tensor.

**Comment by sabinala** [comment]
I'm going to work off of the branch `sa-load-data-tests` instead of the branch `434-add-tests-...` linked to this issue because it looks like something may be off with that branch? It still has a notebook folder with some but not all of the old notebooks from before.

**Comment by SamWitty** [comment]
Closed, as offloaded by our CSV data loader.
