### ISSUE TITLE
Create 'small box' optimize function 

### ISSUE THREAD

**Issue by fivegrant** [ciemss/pyciemss#461]
Optimize-simulate and optimize-calibrate were lost during the refactor. [This issue](https://github.com/DARPA-ASKEM/pyciemss-service/issues/55) is blocked until it's added back

cc @anirban-chaudhuri @liunelson

**Comment by brandomr** [comment]
Any update on adding back in `optimize`?

**Comment by anirban-chaudhuri** [comment]
I have linked the PR that addresses this. It is just awaiting review and should be merge into main today.
