### ISSUE TITLE
Reinclude visualizations

### ISSUE THREAD

**Issue by fivegrant** [ciemss/pyciemss#462]
Visual options were lost during the refactor and may need to be added back in. (this will unblock https://github.com/DARPA-ASKEM/pyciemss-service/issues/53)

cc @liunelson

**Comment by JosephCottam** [comment]
I have a draft version of them back in.  Fidgeting cross-platform testing issues now (it works on multiple machines...it just works a little different).  Hopefully this will be resolved in the next few days.

**Comment by JosephCottam** [comment]
PR #469 (merged today) re-introduces the visualization elements.

**Comment by JosephCottam** [comment]
Closed by #469
