### ISSUE TITLE
Issue with pyro-ppl==1.9.0

### ISSUE THREAD

**Issue by fivegrant** [ciemss/pyciemss#494]
Usually we install `pyciemss` with this command:
```
pip install --no-cache-dir  git+https://github.com/ciemss/pyciemss.git@1fabf279590c613a8ed38d88c6b6faf0c52ba867 --use-pep517
```
however we had to pin `pyro-ppl` like this
``
pip install --no-cache-dir pyro-ppl==1.8.6 git+https://github.com/ciemss/pyciemss.git@1fabf279590c613a8ed38d88c6b6faf0c52ba867 --use-pep517`
``

because we get the following error when importing `pyciemss.interfaces`:
```
../../../.cache/pypoetry/virtualenvs/pyciemss-service-Lm2QylHe-py3.11/lib/python3.11/site-packages/chirho/interventional/handlers.py:121: in <module>
    do = pyro.poutine.handlers._make_handler(Interventions)[1]
E   TypeError: 'function' object is not subscriptable
```

(the issue seems to be with pyro-ppl 1.9.0)

**Comment by SamWitty** [comment]
Thanks for reporting this @fivegrant . We also discovered these issues after the pyro release, and resolved it with this PR. https://github.com/ciemss/pyciemss/pull/486 We'll push another minor release tomorrow in prep for the hackathon which will include this pinning.
