### ISSUE TITLE
Missing values in Optimize results

### ISSUE THREAD

**Issue by liunelson** [ciemss/pyciemss#498]
Optimize currently returns only `policy, OptResults`. However, it used to also return `risk, samples, qoi`.
I think we need `samples` to plot what the optimal intervention policy looks like as a function of time (top of right panel), `qoi` and `risk` to plot the kernel density of the QoI (bottom right of right panel) and the risk threshold value (thick horizontal black line).

![image](https://github.com/ciemss/pyciemss/assets/1030720/78807707-db7c-42e3-a481-0205ec6bba95)

**Comment by liunelson** [comment]
@anirban-chaudhuri 
Is there a plan to bring these results back?

**Comment by anirban-chaudhuri** [comment]
I believe the plan is to just chain `sample` after running optimize. I am working towards bringing some of the original statistics back to the output format from `sample`. This is similar to the change with calibrate. However, you should be able to get back samples using the optimal policy by using 'sample' with the optimal intervention. 
See cell 12 in https://github.com/ciemss/pyciemss/blob/main/docs/source/interfaces.ipynb as an example for chaining optimize-sample. Let me know if this resolves the issue.

**Comment by anirban-chaudhuri** [comment]
I have added risk estimation back into the `sample` interface. See PR #504
