### ISSUE TITLE
Add trajectory-visualization+timepoints tests 

### ISSUE THREAD

**Issue by JosephCottam** [ciemss/pyciemss#506]
PR #505 restored timepoint treatment in the integration interfaces.  The loss was first noticed in the plots.  The PR includes some tests on values, but we should also test that the correct data is shown in the plots.

Suggested path forward: Run `sample` with & without time unit and with a few different sample-frequencies.  Check that the data that is selected includes the correct time-step values as the `timepoint` variable.

**Comment by marjoleinpnnl** [comment]
i'm assuming logging_step_size is the sample-frequency and that it changes the time-step values
