### ISSUE TITLE
Update plotting utils for overlapping distributions

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#51]

**Comment by SamWitty** [comment]
@JosephCottam and @djinnome , is this issue still relevant?

**Comment by djinnome** [comment]
I think so. There are some limitations to vega that make color weaving more technically challenging then it ought to be, so this issue got deprioritized.  @JosephCottam what is the current status on this issue?

**Comment by SamWitty** [comment]
Closed as "will not fix". Can revisit if this becomes a pain point.
