### ISSUE TITLE
Calibration resulted in tensor errors

### ISSUE THREAD

**Issue by mwdchang** [ciemss/pyciemss#526]
We are seeing this error when running calibration, it seems to happen with specific models.

```
ValueError: Expected parameter scale (Tensor of shape (1000,)) of distribution Normal(loc: torch.Size([1000]), scale: torch.Size([1000])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
```

Attached are the inputs for a problematic case we encountered:

[dataset.csv](https://github.com/ciemss/pyciemss/files/14543619/dataset.csv)
[model.json](https://github.com/ciemss/pyciemss/files/14543620/model.json)
[request.json](https://github.com/ciemss/pyciemss/files/14543621/request.json)
[trace.log](https://github.com/ciemss/pyciemss/files/14543622/trace.log)

**Comment by SamWitty** [comment]
@mwdchang , this model does not have a distribution over any of the parameters. In other words, the model is claiming that there is no uncertainty, and thus no parameters can be updated when presented with data. We can add a more informative error message, but the fact that this does not calibrate is expected.
