### ISSUE TITLE
Disappearing observables

### ISSUE THREAD

**Issue by sabinala** [ciemss/pyciemss#552]
Observables disappear when simulating regnet and stockflow models. This is likely a mira issue, but want to be sure before posting it there.

**Comment by sabinala** [comment]
See this notebook for more information: https://github.com/ciemss/pyciemss/blob/552-disappearing-observables/docs/source/Issue552.ipynb

**Comment by sabinala** [comment]
I feel confident now that this is a mira issue, and not a PyCIEMSS problem. @djinnome will you please take a look and confirm that I should post this issue there?

**Comment by djinnome** [comment]
Your notebook was pretty convincing to me. Thanks for taking the time to be so thorough.

**Comment by sabinala** [comment]
Closing as this is not a pyciemss problem and has been posted to mira (see https://github.com/gyorilab/mira/issues/312)
