### ISSUE TITLE
Allow non-constant observables

### ISSUE THREAD

**Issue by sabinala** [ciemss/pyciemss#578]
Currently, parameters in observable expressions must be constant, but we should allow non-constant (or sampled) parameter values.

**Comment by SamWitty** [comment]
@sabinala , I believe observables can already support parameters values in their definitions. Do you have an example where this behavior does not work as expected?

**Comment by sabinala** [comment]
Hi @SamWitty, see here for an example: https://github.com/ciemss/pyciemss/blob/578-allow-non-constant-observables/docs/source/Params-in-observables.ipynb

**Comment by SamWitty** [comment]
Great, thank you. Could you please create an AMR at https://raw.githubusercontent.com/DARPA-ASKEM/simulation-integration/main/data/models/ so that I can add a test when I address this issue. I'll plan on taking this on now.

**Comment by sabinala** [comment]
Here's the PR to add that AMR: https://github.com/DARPA-ASKEM/simulation-integration/pull/78
