### ISSUE TITLE
Add support for multiple constraints in Optimize

### ISSUE THREAD

**Issue by liunelson** [ciemss/pyciemss#583]
From the PI meeting, we discussed allowing users to set multiple constraints (each with their own `alpha`, `qoi`, `observed_params`, `risk_bound`, ...). Terarium's Optimize UI has been modified to support this feature. 

@anirban-chaudhuri are you working on this at the same time as the interventions?

**Comment by anirban-chaudhuri** [comment]
@liunelson I am updating the intervention builder first and then adding support for multiple constraints. It will be a separate PR that I will link here.

**Comment by djinnome** [comment]
Do you have an estimated time for when this will be done?

**Comment by anirban-chaudhuri** [comment]
Should be done within another week.
