### ISSUE TITLE
Optimization with above threshold criteria 

### ISSUE THREAD

**Issue by sabinala** [ciemss/pyciemss#607]
Per Tom and @liunelson's request, can we change the sign of `risk_bound` and `qoi` in `optimize` to change the optimization problem from "keep X below threshold Y" to "keep X above threshold Y"?

**Comment by liunelson** [comment]
This seems to have been resolved by the double minus sign:
* Keep X below some threshold: `qoi = lambda x: np.abs(x), risk_bound = thresh`
* Keep X above some threshold: `qoi = lambda x: -np.abs(x), risk_bound = -thresh`
