### ISSUE TITLE
A Causal Bayesian Workflow for Dynamical Systems

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#623]
An outline for a manuscript that combines:

* PyCIEMSS
* ChiRho $\chi\rho$
* $Y_0$ causal inference engine
* ODEs
* PDEs, surrogate models
* SDEs?
* Multilevel models

**Comment by SamWitty** [comment]
@djinnome , I'd like to keep PyCIEMSS github issues as just things that can be addressed in the library itself. Outlines for manuscripts are out of scope. Closing for now.
