### ISSUE TITLE
Ensemble model results need to be attached to model id rather than number

### ISSUE THREAD

**Issue by sabinala** [ciemss/pyciemss#629]
Currently, ensemble results are given according to the model number. As in `model_0/weight` or `model_0/persistent_beta_c_param` here:

![image](https://github.com/user-attachments/assets/b12575f4-e845-47e1-ab0b-d6d3e9077d39)

TA4 requests that these results include the _model id_ number instead because, per Tom Szendry: The issue with the model order is that we are doing index mapping on indexes that can be updated which is unideal
In other scenarios we may have this `result.csv` without the given call as well so there may be no way to trace back to `model_0`, but there will always be a way to trace back to `ac3c5752-eb02-4ffa-8325-6b4ae9c7891f`.

**Comment by SamWitty** [comment]
From our conversations with Uncharted yesterday it sounds like they are going to be handling the bookkeeping of model ids. Closing this issue as a result.
